/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DateDTO { 
    dateId?: number;
    calDate?: string;
    day?: string;
    week?: number;
    month?: string;
    qtr?: string;
    year?: number;
    holiday?: boolean;
}