/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArrayTypeDTO } from './arrayTypeDTO';
import { BinaryTypeDTO } from './binaryTypeDTO';
import { BooleanTypeDTO } from './booleanTypeDTO';
import { ByteTypeDTO } from './byteTypeDTO';
import { CharTypeDTO } from './charTypeDTO';
import { DateTimeTypeDTO } from './dateTimeTypeDTO';
import { DateTypeDTO } from './dateTypeDTO';
import { DecimalTypeDTO } from './decimalTypeDTO';
import { DoubleTypeDTO } from './doubleTypeDTO';
import { FloatTypeDTO } from './floatTypeDTO';
import { IntegerTypeDTO } from './integerTypeDTO';
import { LongTypeDTO } from './longTypeDTO';
import { MapTypeDTO } from './mapTypeDTO';
import { NullDataTypeDTO } from './nullDataTypeDTO';
import { ShortTypeDTO } from './shortTypeDTO';
import { StringTypeDTO } from './stringTypeDTO';
import { StructTypeDTO } from './structTypeDTO';

export interface StructFieldDTO { 
    name?: string;
    dataType?: ArrayTypeDTO | BinaryTypeDTO | BooleanTypeDTO | ByteTypeDTO | CharTypeDTO | DateTimeTypeDTO | DateTypeDTO | DecimalTypeDTO | DoubleTypeDTO | FloatTypeDTO | IntegerTypeDTO | LongTypeDTO | MapTypeDTO | NullDataTypeDTO | ShortTypeDTO | StringTypeDTO | StructTypeDTO;
    nullable?: boolean;
}