/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDTO { 
    userId?: number;
    userName?: string;
    firstName?: string;
    lastName?: string;
    city?: string;
    state?: string;
    email?: string;
    phone?: string;
    likeSports?: boolean;
    likeTheatre?: boolean;
    likeConcerts?: boolean;
    likeJazz?: boolean;
    likeClassical?: boolean;
    likeOpera?: boolean;
    likeRock?: boolean;
    likeVegas?: boolean;
    likeBroadway?: boolean;
    likeMusicals?: boolean;
}